// biome-ignore format: generated file — run `npm run fixtures:update` to refresh
// Auto-generated by scripts/capture-fixtures.ts
// Last captured: 2026-03-28T07:47:08.692Z
// Run `npm run fixtures:update` to replace with real Museum header data

export const MUSEUM_CAPTURED_AT = '2026-03-28T07:47:08.692Z';

/**
 * Ordered tuple of all Museum worksheet column headers in sheet order.
 * Auto-generated by scripts/capture-fixtures.ts — do not edit manually.
 */
export const MUSEUM_FIELDS = [
	'moo:workingNotes',
	'moo:tags',
	'dcterms:Collection',
	'dcterms:identifier.moooi',
	'dcterms:identifier.moooiqr',
	'dcterms:dateAccepted',
	'dcterms:accrualMethod',
	'dcterms:source.acquisition',
	'dcterms:provenance',
	'dcterms:title',
	'dcterms:alternative',
	'dcterms:type',
	'dcterms:format',
	'dcterms:identifier.isbn',
	'dcterms:creator',
	'dcterms:creator.mooRef',
	'dcterms:creator.troveRef',
	'dcterms:creator.sroRef',
	'moo:relatedEntities',
	'moo:relatedEntities.mooRef',
	'moo:relatedEntities.troveRef',
	'moo:relatedEntities.sroRef',
	'dcterms:created',
	'dcterms:Jurisdiction',
	'dcterms:spatial',
	'dcterms:spatial.uri',
	'dcterms:temporal',
	'dcterms:publisher',
	'dcterms:dateCopyrighted',
	'dcterms:contributor.author',
	'dcterms:description',
	'dcterms:image',
	'dcterms:description.condition',
	'dcterms:Location',
	'dcterms:Location.qr',
	'dwc:higherGeography',
	'dwc:higherGeographyID',
	'dwc:eventDate',
	'dcterms:rights',
	'dcterms:rightsHolder',
	'dcterms:extent',
	'dcterms:tableOfContents',
] as const;

/** Union of all Museum column name literals. */
export type MuseumField = (typeof MUSEUM_FIELDS)[number];

/**
 * Museum column names in sheet order.
 * Used as the header row in buildMuseumResponse().
 */
export const museumFieldOrder: string[] = [...MUSEUM_FIELDS];
